### ISSUE TITLE
Prolems encounted in handling DDA data acquired using Waters Xevo G2-XS Qtof

### ISSUE THREAD

**Issue by xieyying** [elnurgar/mzxml-precursor-corrector#1]
This program will be very helpful for the users of waters mass spectrometers. I use Waters Xevo G2-XS Qtof and when I convert the DDA data using Msconvert. I also encount the problem that the precursors have high errors. But when I try to correct the precusor using mzxml-precursor-corrector and found it does not work for my data. I want to know if this program can deal with DDA data acquired by Waters Xevo G2-XS Qtof? Thanks

**Comment by elnurgar** [comment]
Hi,

Can you please share some of your mzxml files? I will check it.

Thank you

**Comment by xieyying** [comment]
Sure, my mzML file is attached. 
Thanks













--

Yunying Xie, Professor
Institute of Medicinal Biotechnology,

Chinese Academy of Medical Sciences & Peaking Union Medical college
Tiantan No.1, Beijing, China




At 2023-03-23 15:59:19, "elnurgar" ***@***.***> wrote:

Hi,

Can you please share some of your mzxml files? I will check it.

Thank you

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
20200425_enniatin_A1_A7_A10-B7_DDA_300-10-50-150_M27.mzML (96.68M, 2023年4月22日 23:47 到期)
下载

**Comment by elnurgar** [comment]
Sorry,

I don't see your file. Maybe the file is very large.

**Comment by elnurgar** [comment]
Can you send me the link to google drive or to dropbox?

**Comment by xieyying** [comment]
Here is the google driver link for the data: https://drive.google.com/drive/folders/1QZBLos74qRyH4Acosvbu6YyK5ZpZtaom?usp=sharing
Thanks























--




At 2023-03-24 05:50:54, "elnurgar" ***@***.***> wrote:

Can you send me the link to google drive or to dropbox?

**Comment by elnurgar** [comment]
@xieyying please try with the new release. Actually, in your mzml file you have many scans with internal reference marked as msLevel 0. Try now please with the new release and keep me informed.

**Comment by elnurgar** [comment]
@xieyying try to increase the error window if the problems still persists

**Comment by xieyying** [comment]
Thanks very much. It works well now. Yes. my data include UV signals. These signals were set as mslevel 0 when I converted using Msconvert.













--




At 2023-03-24 22:01:42, "elnurgar" ***@***.***> wrote:

@xieyying try to increase the error window if the problems still persists

**Comment by elnurgar** [comment]
Glad to hear that it works.
