### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ADablanc** [elnurgar/mzxml-precursor-corrector#2]
Hello !

I have an issue when trying correcting a waters raw file.
![image](https://user-images.githubusercontent.com/109523515/230038756-0ca1cd70-d68d-4a67-995d-9b044f7fe8dc.png)

**Comment by elnurgar** [comment]
Hi. Can you send me please your raw data by google drive? Thank u.

**Comment by elnurgar** [comment]
Sorry, I understand your problem. Please into the lockmass list insert your values. 554.2615 is for neg mode and 556.2771 for pos mode. You need to type only 1 for waters. Try this if doesn't work send me your data I will check

**Comment by ADablanc** [comment]
oh! Sorry for that, thank you !

**Comment by ADablanc** [comment]
Hi. I tested a new time with only 556.2771 but still not working:
![image](https://user-images.githubusercontent.com/109523515/230400350-1ab5d723-d419-41af-a261-5a23f9a65f60.png)

Link to Google Drive: https://drive.google.com/drive/folders/1dkwl_NgZTRivlF2vZg602Z4RcU2xkYx3?usp=share_link

**Comment by elnurgar** [comment]
hi, I have just checked your data. There are no ms2 scans at all. That's why it doesn't work.

**Comment by elnurgar** [comment]
If it is ok for you I close the issue.
